"""update permit

Revision ID: 3fba64071833
Revises: d2ff42dc7443
Create Date: 2023-08-28 14:50:45.943845

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3fba64071833'
down_revision = 'd2ff42dc7443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
                    sa.Column('permit_id', sa.BigInteger(), nullable=False),
                    sa.Column('location_id', sa.BigInteger(), nullable=False),
                    sa.Column('permit_type_name', sa.String(length=100), nullable=False),
                    sa.Column('occupancy_type', sa.String(length=100), nullable=True),
                    sa.Column('date_created', sa.Date(), nullable=True),
                    sa.Column('date_submitted', sa.Date(), nullable=True),
                    sa.Column('address_id', sa.BigInteger(), nullable=False),
                    sa.Column('applicant_full_name', sa.String(length=100), nullable=True),
                    sa.Column('property_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['prod.address.address_id'], ),
                    sa.ForeignKeyConstraint(['property_id'], ['prod.property.property_id'], ),
                    sa.PrimaryKeyConstraint('permit_id'),
                    schema='prod'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit', schema='prod')
    # ### end Alembic commands ###
